tap 'homebrew/services'

# Core command-center baseline (safe on fresh hosts)
brew 'tmux'
brew 'rg'
brew 'fzf'
brew 'fd'
brew 'jq'
brew 'htop'
brew 'tree'
brew 'coreutils'
brew 'trash'
brew 'zsh'
brew 'openssl'
brew 'pkg-config'
