#!/usr/bin/env bash
#
# create-pr.sh - Hook to create GitHub PR on build completion
#
# This hook is triggered on_build_complete to automatically create a GitHub
# pull request for the current branch. It extracts PR title and description
# from the implementation plan and uses gh CLI for PR creation.
#
# Prerequisites:
#   - gh CLI installed and authenticated (https://cli.github.com/)
#   - Current directory is a git repository
#   - Current branch is pushed to remote
#
# Environment Variables (provided by wiggum):
#   WIGGUM_PLAN_FILE    - Path to the implementation plan file
#   WIGGUM_PROJECT_ROOT - Project root directory path
#
# Exit Codes:
#   0 - Success (or gh not available, or on main branch, or PR exists)
#   1 - PR creation failed
#

set -euo pipefail

# Change to project root
cd "${WIGGUM_PROJECT_ROOT:-.}"

# Check if gh CLI is available
if ! command -v gh >/dev/null 2>&1; then
  echo "WARNING: gh CLI not found in PATH - skipping PR creation" >&2
  echo "Install gh CLI to enable automatic PR creation: https://cli.github.com/" >&2
  exit 0
fi

# Get current branch name
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")

if [[ -z "$CURRENT_BRANCH" ]]; then
  echo "ERROR: Failed to get current branch name" >&2
  exit 1
fi

# Skip PR creation if on main or master branch
if [[ "$CURRENT_BRANCH" == "main" || "$CURRENT_BRANCH" == "master" ]]; then
  echo "INFO: On $CURRENT_BRANCH branch - skipping PR creation" >&2
  exit 0
fi

# Check if PR already exists for this branch
if gh pr view --json number >/dev/null 2>&1; then
  PR_NUMBER=$(gh pr view --json number --jq '.number' 2>/dev/null || echo "")
  echo "INFO: PR already exists for branch $CURRENT_BRANCH (PR #$PR_NUMBER)" >&2
  exit 0
fi

# Generate PR title from plan file
PR_TITLE=""
PR_SUMMARY=""

if [[ -n "${WIGGUM_PLAN_FILE:-}" ]] && [[ -f "$WIGGUM_PLAN_FILE" ]]; then
  # Extract overview section as summary (first non-empty paragraph after ## Overview)
  PR_SUMMARY=$(awk '
    /^## Overview/ { in_overview=1; next }
    in_overview && /^##/ { exit }
    in_overview && NF > 0 {
      if (!started) started=1
      if (started) print
    }
  ' "$WIGGUM_PLAN_FILE" | head -20)

  # Generate title from overview summary or fallback to first task
  if [[ -n "$PR_SUMMARY" ]]; then
    # Use first sentence of overview as title
    PR_TITLE=$(echo "$PR_SUMMARY" | head -1 | sed 's/\. .*//' | head -c 80)
  else
    # Fallback: extract first completed task description
    PR_TITLE=$(awk '
      /^### [0-9]+\./ {
        getline;
        if ($0 ~ /Status.*completed/) {
          while (getline) {
            if ($0 ~ /^- \*\*Description\*\*:/) {
              sub(/^- \*\*Description\*\*: /, "")
              print
              exit
            }
          }
        }
      }
    ' "$WIGGUM_PLAN_FILE" | head -c 80)
  fi
fi

# Fallback title if extraction failed
if [[ -z "$PR_TITLE" ]]; then
  PR_TITLE="Implement changes from $CURRENT_BRANCH"
fi

# Build PR body
PR_BODY=$(cat <<EOF
## Summary

${PR_SUMMARY:-Automated implementation from wiggum build process.}

## Implementation Plan

See [IMPLEMENTATION_PLAN.md](IMPLEMENTATION_PLAN.md) for full details.

---
*Generated by [wiggum](https://github.com/anthropics/wiggum)*
EOF
)

# Create the pull request
echo "Creating pull request for branch $CURRENT_BRANCH..." >&2

if gh pr create \
  --title "$PR_TITLE" \
  --body "$PR_BODY" \
  --fill-verbose 2>&1; then

  # Get the new PR number
  PR_NUMBER=$(gh pr view --json number --jq '.number' 2>/dev/null || echo "")
  echo "Successfully created PR #$PR_NUMBER" >&2
  exit 0
else
  echo "ERROR: Failed to create pull request" >&2
  exit 1
fi
